FROM ghcr.io/zegnhabi/at:latest AS app
FROM nginx:alpine
COPY --from=app /var/www/html/public /var/www/html/public
COPY --from=app /var/www/html/storage /var/www/html/storage
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
