<?php
$title="Bus Ticketing SQLeros.Com.Ar [ Homepage]";
$title2="Bus Ticketing  SQLeros.Com.Ar [ Select run ]";
$title3="Bus Ticketing  SQLeros.Com.Ar[ Choose Seats ]";
$title4="Bus Ticketing  SQLeros.Com.Ar[ Buy Tickets ]";
$title5="Bus Ticketing  SQLeros.Com.Ar[ Print Tickets ]";
$selectLenguaje="Select Language";
$selectOrigen="Select Provenance";
$selectDestino="Select Destination";
$contacto="Contact";
$error="Please go to the <a href=\"\" >homepage </a>";
$excepcion="An exception has occurred. Please go to the <a href=\"\" >homepage </a>";
$corridaSinAsientos="the run has no seats available. Select another. Back to <a href=\"\" >homepage </a>";
$fechaIda="Departure date";
$xorigen="Provenance";
$xdestino="Destination";
$xhorario="schedule";
$xtarifa="Price";
$tiempoRecorrido="Travel time";
$selectAsientos="Choose seats";
$xfecha="Date";
$xhora="Time";
$xD="From";
$xA="To";
$selectNumBoletos="Select the number of tickets";
$AsientoOcupado="Seat Occupied";
$AsientoDisponible="Available Seat";
$AsientoSeleccionado="Seat Selected";
$ComprarBoletos="Buy Tickets";
$Asientos="Seating";
$NombreDelPasajero="Passenger Name";
$SeHanComprado="Have been purchased: ";
$Boletos="Ticket(s).";
$Imprimir="Print";
$Inicio="Homepage";
$Terminaldesalida="Terminal of origin:";
$Terminaldellegada="Arrival terminal:";
$Fechadesalida="Departure date:";
$Asiento="Seat:";
$Horadesalida="Departure time:";
$Precio="Price:";
$Nombre="Name:";
$LugaryfechadeEx="Place and date of purchase:";
$sugerencia="Keep your ticket,<br /> Is your travel insurance.";
?>