<?php
$title="Boletaje Autobuses SQLeros.Com.Ar [ P&aacute;gina Principal ]";
$title2="Boletaje Autobuses SQLeros.Com.Ar [ Seleccionar Corrida ]";
$title3="Boletaje Autobuses SQLeros.Com.Ar[ Elegir Asientos ]";
$title4="Boletaje Autobuses SQLeros.Com.Ar[ Comprar Boletos ]";
$title5="Boletaje Autobuses SQLeros.Com.Ar[ Imprimir Boletos ]";
$selectLenguaje="Seleccione Lenguaje";
$selectOrigen="Seleccione Origen";
$selectDestino="Seleccione Destino";
$contacto="Contacto";
$error="Por Favor Ingrese A La <a href=\"\" >P&aacute;gina Principal.";
$excepcion="Ha Sucedido Una Excepci&oacute;n Por Favor Ingrese A La <a href=\"\" >P&aacute;gina Principal.";
$corridaSinAsientos="La Corrida ya no tiene asientos Libres. Seleccione otra. <a 
	href=\"\" >Volver P&aacute;gina Principal.</a>";
$fechaIda="Fecha de Ida";
$xorigen="Origen";
$xdestino="Destino";
$xhorario="Horario";
$xtarifa="Tarifa";
$tiempoRecorrido="Tiempo de recorrido";
$selectAsientos="Elegir Asientos";
$xfecha="Fecha";
$xhora="Hora";
$xD="De";
$xA="A";
$selectNumBoletos="Selecciona el numero de boletos";
$AsientoOcupado="Asiento Ocupado";
$AsientoDisponible="Asiento Disponible";
$AsientoSeleccionado="Asiento Seleccionado";
$ComprarBoletos="Comprar Boletos";
$Asientos="Asientos";
$NombreDelPasajero="Nombre Del Pasajero";
$SeHanComprado="Se Han Comprado: ";
$Boletos="Boleto(s).";
$Imprimir="Imprimir";
$Inicio="Inicio";
$Terminaldesalida="Terminal de salida:";
$Terminaldellegada="Terminal de llegada:";
$Fechadesalida="Fecha de salida:";
$Asiento="Asiento:";
$Horadesalida="Hora de salida:";
$Precio="Precio:";
$Nombre="Nombre:";
$LugaryfechadeEx="Lugar y fecha de expedici&oacute;n:";
$sugerencia="Conserve su boleto, es <br /> su seguro de viajero.";
?>